#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#
# Do not move this debug line !!!
if [ -n "${ZSH_DEBUGRC+1}" ]; then
    zmodload zsh/zprof
fi

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
# Source Conda
if [[ -s "${ZDOTDIR:-$HOME/.zprezto/conda.zsh}" ]]; then
  source "${ZDOTDIR:-$HOME/.zprezto/conda.zsh}"
fi

# Source config
if [[ -s "${ZDOTDIR:-$HOME/.zprezto/config.zsh}" ]]; then
  source "${ZDOTDIR:-$HOME/.zprezto/config.zsh}"
fi

# Source aliases
if [[ -s "${ZDOTDIR:-$HOME/.zprezto/aliases.zsh}" ]]; then
  source "${ZDOTDIR:-$HOME/.zprezto/aliases.zsh}"
fi

# Source Environment variables
if [[ -s "${ZDOTDIR:-$HOME/.zprezto/env.zsh}" ]]; then
  source "${ZDOTDIR:-$HOME/.zprezto/env.zsh}"
fi

# Source zoxide
if command -v zoxide &> /dev/null; then
  eval "$(zoxide init zsh --cmd cd)"
fi

if [[ -s "$HOME/.atuin/bin/env" ]]; then
  . "$HOME/.atuin/bin/env"
  eval "$(atuin init zsh)"
fi


# This must always be ath the end of the file!!
if [ -n "${ZSH_DEBUGRC+1}" ]; then
    zprof
fi
alias zsh-profile='time ZSH_DEBUGRC=1 zsh -i -c exit'
